openapi: 3.0.1
info:
  title: gia
  version: '1.0'
  description: The entry point is https://gia-api.herokuapp.com
servers:
  - url: /
paths:
  /books:
    get:
      description: return an array of books
      parameters:
        - name: API_KEY
          in: query
          description: |
            API KEY
          required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
  /score:
    get:
      description: return a single gia score at a specified latitude and longitude
      parameters:
        - name: API_KEY
          in: query
          description: |
            API KEY
          required: true
        - name: lat
          in: query
          description: |
            Latitude
          required: true
          style: form
          explode: true
          schema:
            type: string
        - name: lon
          in: query
          description: |
            Longitude
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Score'
  /saturation:
    get:
      description: return a count and total amount of policy limits within a specified radius of a specified latitude and longitude
      parameters:
        - name: API_KEY
          in: query
          description: |
            API KEY
          required: true
        - name: lat
          in: query
          description: |
            Latitude
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: lon
          in: query
          description: |
            Longitude
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: rad
          in: query
          description: |
            Radius
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Saturation'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        count:
          type: integer
          format: int32
        scored:
          type: integer
          format: int32
    Score:
      type: object
      properties:
        id:
          type: integer
          format: int32
        score:
          type: integer
          format: int32
    Saturation:
      type: object
      properties:
        count:
          type: integer
          format: int32
        total:
          type: integer
          format: int32
